import 'option.dart';

class OptionInterpreter {
  static final Map<String, Function> initializerMap = {
    "Normal": OPTION.initializeNormal,
    "Quiet": OPTION.initializeQuiet,
    "Fearful": OPTION.initializeFearful,
    "Withdrawn": OPTION.initializeWithdrawn,
    "Aggressive": OPTION.initializeAggressive,
    "Disoriented": OPTION.initializeDisoriented,
    "Demented": OPTION.initializeDemented,
    "Sleep/Wake Cycle Change": OPTION.initializeSleepWakeCycleChange,
    "Voiding in House": OPTION.initializeVoidingInHouse,
    "Loss of train behavior": OPTION.initializeLossOfTrainBehavior,
    "Circling - Right": OPTION.initializeCirclingRight,
    "Circling - Left": OPTION.initializeCirclingLeft,
    "Circling - Both": OPTION.initializeCirclingBoth,
    "Compulsive Walking": OPTION.initializeCompulsiveWalking,
    "Head Pressing": OPTION.initializeHeadPressing,
    "Other": OPTION.initializeOther,
    "Alert": OPTION.initializeAlert,
    "Lethargic": OPTION.initializeLethargic,
    "Obtunded": OPTION.initializeObtunded,
    "Stuporous": OPTION.initializeStuporous,
    "Comatose": OPTION.initializeComatose,
    "Normal Posture": OPTION.initializeNormalPosture,
    "Head Tilt - Right": OPTION.initializeHeadTiltRight,
    "Head Tilt - Left": OPTION.initializeHeadTiltLeft,
    "Head Turn - Right": OPTION.initializeHeadTurnRight,
    "Head Turn - Left": OPTION.initializeHeadTurnLeft,
    "Torticollis": OPTION.initializeTorticollis,
    "Neck Guarded": OPTION.initializeNeckGuarded,
    "Archer Posture": OPTION.initializeArcherPosture,
    "Holding Up Limb": OPTION.initializeHoldingUpLimb,
    "Laterally Recumbent": OPTION.initializeLaterallyRecumbent,
    "Decerebrate": OPTION.initializeDecerebrate,
    "Decerebellate": OPTION.initializeDecerebellate,
    "Opisthotonus": OPTION.initializeOpisthotonus,
    "Schiff-Sherrington": OPTION.initializeSchiffSherrington,
    "Kyphosis": OPTION.initializeKyphosis,
    "Scoliosis": OPTION.initializeScoliosis,
    "Diffuse Rigidity": OPTION.initializeDiffuseRigidity,
    "Risus Sardonicus": OPTION.initializeRisusSardonicus,
    "Diffuse Flaccidity": OPTION.initializeDiffuseFlaccidity,
    "Spastic - Thoracic Limbs": OPTION.initializeSpasticThoracicLimbs,
    "Spastic - Pelvic Limbs": OPTION.initializeSpasticPelvicLimbs,
    "Spastic - All Limbs": OPTION.initializeSpasticAllLimbs,
    "Crouched Posture - Thoracic Limbs": OPTION.initializeCrouchedPostureThoracicLimbs,
    "Crouched Posture - Pelvic Limbs": OPTION.initializeCrouchedPosturePelvicLimbs,
    "Crouched Posture - All Limbs": OPTION.initializeCrouchedPostureAllLimbs,
    "Praying Posture": OPTION.initializePrayingPosture,
    "Ambulatory - Normal": OPTION.initializeAmbulatoryNormal,
    "Ambulatory - Lameness Thoracic Limb": OPTION.initializeAmbulatoryLamenessThoracic,
    "Ambulatory - Lameness Pelvic Limb": OPTION.initializeAmbulatoryLamenessPelvic,
    "Ambulatory - Monoparesis Thoracic Limb": OPTION.initializeAmbulatoryMonoparesisThoracic,
    "Ambulatory - Monoparesis Pelvic Limb": OPTION.initializeAmbulatoryMonoparesisPelvic,
    "Ambulatory - Monoplegia Thoracic Limb": OPTION.initializeAmbulatoryMonoplegiaThoracic,
    "Ambulatory - Monoplegia Pelvic Limb": OPTION.initializeAmbulatoryMonoplegiaPelvic,
    "Ambulatory - Paraparesis Thoracic Limb": OPTION.initializeAmbulatoryParaparesisThoracic,
    "Ambulatory - Paraparesis Pelvic Limb": OPTION.initializeAmbulatoryParaparesisPelvic,
    "Ambulatory - Tetraparesis": OPTION.initializeAmbulatoryTetraparesis,
    "Ambulatory - Short Strided Thoracic Limb": OPTION.initializeAmbulatoryShortStridedThoracic,
    "Ambulatory - Short Strided Pelvic Limb": OPTION.initializeAmbulatoryShortStridedPelvic,
    "Ambulatory - Short Strided All Limbs": OPTION.initializeAmbulatoryShortStridedAll,
    "Ambulatory - 2-Engine Gait": OPTION.initializeAmbulatory2EngineGait,
    "Ambulatory - Paraparesis Pelvic Limbs with Proprioceptive Ataxia": OPTION.initializeAmbulatoryParaparesisPelvicProprioceptiveAtaxia,
    "Ambulatory - Tetraparesis with Proprioceptive Ataxia": OPTION.initializeAmbulatoryTetraparesisProprioceptiveAtaxia,
    "Ambulatory - Proprioceptive Ataxia Pelvic Limb": OPTION.initializeAmbulatoryProprioceptiveAtaxiaPelvic,
    "Ambulatory - Proprioceptive Ataxia All Limbs": OPTION.initializeAmbulatoryProprioceptiveAtaxiaAll,
    "Ambulatory - Fatiguable": OPTION.initializeAmbulatoryFatiguable,
    "Ambulatory - Tetraparesis with Vestibular Ataxia": OPTION.initializeAmbulatoryTetraparesisVestibularAtaxia,
    "Ambulatory - Tetraparesis with Cerebellar Ataxia": OPTION.initializeAmbulatoryTetraparesisCerebellarAtaxia,
    "Ambulatory - Vestibular Ataxia": OPTION.initializeAmbulatoryVestibularAtaxia,
    "Ambulatory - Cerebellar Ataxia": OPTION.initializeAmbulatoryCerebellarAtaxia,
    "Ambulatory - Mixed Ataxia": OPTION.initializeAmbulatoryMixedAtaxia,
    "Ambulatory - Mixed Ataxia with Tetraparesis": OPTION.initializeAmbulatoryMixedAtaxiaTetraparesis,
    "Ambulatory - Hemiparesis Left": OPTION.initializeAmbulatoryHemiparesisLeft,
    "Ambulatory - Hemiparesis Left with Proprioceptive Ataxia": OPTION.initializeAmbulatoryHemiparesisLeftProprioceptiveAtaxia,
    "Ambulatory - Hemiparesis Left with Cerebellar Ataxia": OPTION.initializeAmbulatoryHemiparesisLeftCerebellarAtaxia,
    "Ambulatory - Hemiparesis Left with Mixed Ataxia": OPTION.initializeAmbulatoryHemiparesisLeftMixedAtaxia,
    "Ambulatory - Hemiparesis Left with Vestibular Ataxia": OPTION.initializeAmbulatoryHemiparesisLeftVestibularAtaxia,
    "Ambulatory - Hemiparesis Right": OPTION.initializeAmbulatoryHemiparesisRight,
    "Ambulatory - Hemiparesis Right with Proprioceptive Ataxia": OPTION.initializeAmbulatoryHemiparesisRightProprioceptiveAtaxia,
    "Ambulatory - Hemiparesis Right with Cerebellar Ataxia": OPTION.initializeAmbulatoryHemiparesisRightCerebellarAtaxia,
    "Ambulatory - Hemiparesis Right with Mixed Ataxia": OPTION.initializeAmbulatoryHemiparesisRightMixedAtaxia,
    "Ambulatory - Hemiparesis Right with Vestibular Ataxia": OPTION.initializeAmbulatoryHemiparesisRightVestibularAtaxia,
    "None": OPTION.initializeNone,
    "Seizures - Focal": OPTION.initializeSeizuresFocal,
    "Seizures - Generalized": OPTION.initializeSeizuresGeneralized,
    "Tremors - Action Related": OPTION.initializeTremorsActionRelated,
    "Tremors - Constant": OPTION.initializeTremorsConstant,
    "Tremors - Episodic": OPTION.initializeTremorsEpisodic,
    "Tremors - When Standing": OPTION.initializeTremorsWhenStanding,
    "Paroxysmal Event": OPTION.initializeParoxysmalEvent,
    "Myoclonus - Cervical": OPTION.initializeMyoclonusCervical,
    "Myoclonus - Constant": OPTION.initializeMyoclonusConstant,
    "Myoclonus - Episodic": OPTION.initializeMyoclonusEpisodic,
    "Myokymia": OPTION.initializeMyokymia,
    "(Neuro) Myotonia": OPTION.initializeNeuroMyotonia,
    "Narcolepsy": OPTION.initializeNarcolepsy,
    "Head Swaying": OPTION.initializeHeadSwaying,
  };

  static List<Function> interpret(List<String> selectedOptions) {
    List<Function> initializers = [];
    for (String optionName in selectedOptions) {
      var initializer = initializerMap[optionName];
      if (initializer != null) {
        initializers.add(initializer);
      }
    }
    return initializers;
  }
}
