import 'dashboard_globals.dart';


class DashboardModel {
    // A map that holds another map for each behavior.
    Map<String, Map<String, int>> behaviors = {
        'Normal': {
          'normalExam': normalNormalExam,
          'rightForebrain': normalRightForebrain,
          'leftForebrain': normalLeftForebrain,
          'behavioral': normalBehavioral,
          'intercranial': normalIntercranial,
        },
        'quiet': {
          'normalExam': quietNormalExam,
        },
        'fearful': {
          'forebrain': fearfulForebrain,
          'rightForebrain': fearfulForebrain,
          'leftForebrain': fearfulLeftForebrain,
          'behavioral': fearfulBehavioral,
          'systemicIllness': fearfulSystemicIllness,
          'intracranial': fearfulIntracranial,
          'nonSpecificPain': fearfulNonSpecificPain,
          'openEtiology': fearfulOpenEtiology,
          'cervicalPain': fearfulCervicalPain,
        },

      'withdrawn': {
        'forebrain': withdrawnForebrain,
        'rightForebrain': withdrawnRightForebrain,
        'leftForebrain': withdrawnLeftForebrain,
        'behavioral': withdrawnBehavioral,
        'systemicIllness': withdrawnSystemicIllness,
        'intracranial': withdrawnIntracranial,
        'nonSpecificPain': withdrawnNonSpecificPain,
        'openEtiology': withdrawnOpenEtiology,
        'cervicalPain': withdrawnCervicalPain,
      },
      'aggressive': {
        'forebrain': aggressiveForebrain,
        'rightForebrain': aggressiveRightForebrain,
        'leftForebrain': aggressiveLeftForebrain,
        'behavioral': aggressiveBehavioral,
        'systemicIllness': aggressiveSystemicIllness,
        'intracranial': aggressiveIntracranial,
        'nonSpecificPain': aggressiveNonSpecificPain,
        'openEtiology': aggressiveOpenEtiology,
        'cervicalPain': aggressiveCervicalPain,
      },
      'disoriented': {
        'forebrain': disorientedForebrain,
        'rightForebrain': disorientedRightForebrain,
        'leftForebrain': disorientedLeftForebrain,
        'vestibular': disorientedVestibular,
        'rightPeripheralVestibular': disorientedRightPeripheralVestibular,
        'rightCentralVestibular': disorientedRightCentralVestibular,
        'leftPeripheralVestibular': disorientedLeftPeripheralVestibular,
        'leftCentralVestibular': disorientedLeftCentralVestibular,
        'cerebellum': disorientedCerebellum,
        'rightCerebellumParadoxical': disorientedRightCerebellumParadoxical,
        'leftCerebellumParadoxical': disorientedLeftCerebellumParadoxical,
        'behavioral': disorientedBehavioral,
        'systemicIllness': disorientedSystemicIllness,
        'intracranial': disorientedIntracranial,
        'openEtiology': disorientedOpenEtiology,
      },

       'demented': {
          'forebrain': dementedForebrain,
          'rightForebrain': dementedRightForebrain,
          'leftForebrain': dementedLeftForebrain,
          'behavioral': dementedBehavioral,
          'intracranial': dementedIntracranial,
          'openEtiology': dementedOpenEtiology,
      },
      'sleepWakeCycleChange': {
          'forebrain': sleepWakeCycleChangeForebrain,
          'rightForebrain': sleepWakeCycleChangeRightForebrain,
          'leftForebrain': sleepWakeCycleChangeLeftForebrain,
          'behavioral': sleepWakeCycleChangeBehavioral,
          'intracranial': sleepWakeCycleChangeIntracranial,
          'openEtiology': sleepWakeCycleChangeOpenEtiology,
      },
      'voidingInHouse': {
          'forebrain': voidingInHouseForebrain,
          'rightForebrain': voidingInHouseRightForebrain,
          'leftForebrain': voidingInHouseLeftForebrain,
          'c1C5Myelopathy': voidingInHouseC1C5Myelopathy,
          't3L3Myelopathy': voidingInHouseT3L3Myelopathy,
          'l4S3Myelopathy': voidingInHouseL4S3Myelopathy,
          'caudaEquina': voidingInHouseCaudaEquina,
          's1S3': voidingInHouseS1S3,
          'behavioral': voidingInHouseBehavioral,
          'intracranial': voidingInHouseIntracranial,
          'nonSpecificPain': voidingInHouseNonSpecificPain,
          'openEtiology': voidingInHouseOpenEtiology,
      },
        'lossOfTrainBehavior': {
    'forebrain': lossOfTrainBehaviorForebrain,
    'rightForebrain': lossOfTrainBehaviorRightForebrain,
    'leftForebrain': lossOfTrainBehaviorLeftForebrain,
    'behavioral': lossOfTrainBehaviorBehavioral,
    'intracranial': lossOfTrainBehaviorIntracranial,
    'openEtiology': lossOfTrainBehaviorOpenEtiology,
},
'circlingRight': {
    'forebrain': circlingRightForebrain,
    'rightForebrain': circlingRightRightForebrain,
    'brainstem': circlingRightBrainstem,
    'vestibular': circlingRightVestibular,
    'rightPeripheralVestibular': circlingRightRightPeripheralVestibular,
    'rightCentralVestibular': circlingRightRightCentralVestibular,
    'leftCerebellumParadoxical': circlingRightLeftCerebellumParadoxical,
    'intracranial': circlingRightIntracranial,
},
'circlingLeft': {
    'forebrain': circlingLeftForebrain,
    'leftForebrain': circlingLeftLeftForebrain,
    'brainstem': circlingLeftBrainstem,
    'vestibular': circlingLeftVestibular,
    'leftPeripheralVestibular': circlingLeftLeftPeripheralVestibular,
    'leftCentralVestibular': circlingLeftLeftCentralVestibular,
    'rightCerebellumParadoxical': circlingLeftRightCerebellumParadoxical,
    'intracranial': circlingLeftIntracranial,
},
'circlingBoth': {
    'forebrain': circlingBothForebrain,
    'intracranial': circlingBothIntracranial,
    'behavioral': circlingBothBehavioral,
},
'compulsiveWalking': {
    'forebrain': compulsiveWalkingForebrain,
    'rightForebrain': compulsiveWalkingRightForebrain,
    'leftForebrain': compulsiveWalkingLeftForebrain,
    'behavioral': compulsiveWalkingBehavioral,
    'intracranial': compulsiveWalkingIntracranial,
},
'headPressing': {
    'forebrain': headPressingForebrain,
    'rightForebrain': headPressingRightForebrain,
    'leftForebrain': headPressingLeftForebrain,
    'intracranial': headPressingIntracranial,
},


'other': {
    'behavioral': otherBehavioral,
    'forebrain': otherForebrain,
    'rightForebrain': otherRightForebrain,
    'leftForebrain': otherLeftForebrain,
    'systemicIllness': otherSystemicIllness,
    'intracranial': otherIntracranial,
    'openEtiology': otherOpenEtiology,
},
'none': {
    'normalExam': noneNormalExam,
},
'seizuresFocal': {
    'forebrain': seizuresFocalForebrain,
    'rightForebrain': seizuresFocalRightForebrain,
    'leftForebrain': seizuresFocalLeftForebrain,
    'intracranial': seizuresFocalIntracranial,
},
'seizuresGeneralized': {
    'forebrain': seizuresGeneralizedForebrain,
    'rightForebrain': seizuresGeneralizedRightForebrain,
    'leftForebrain': seizuresGeneralizedLeftForebrain,
    'intracranial': seizuresGeneralizedIntracranial,
},
'tremorsActionRelated': {
    'cerebellum': tremorsActionRelatedCerebellum,
    'neuromuscular': tremorsActionRelatedNeuromuscular,
    'intracranial': tremorsActionRelatedIntracranial,
    'openEtiology': tremorsActionRelatedOpenEtiology,
},
'tremorsConstant': {
    'cerebellum': tremorsConstantCerebellum,
    'neuromuscular': tremorsConstantNeuromuscular,
    'intracranial': tremorsConstantIntracranial,
    'openEtiology': tremorsConstantOpenEtiology,
},
'tremorsEpisodic': {
    'forebrain': tremorsEpisodicForebrain,
    'rightForebrain': tremorsEpisodicRightForebrain,
    'leftForebrain': tremorsEpisodicLeftForebrain,
    'intracranial': tremorsEpisodicIntracranial,
    'openEtiology': tremorsEpisodicOpenEtiology,
},
'tremorsWhenStanding': {
    'cerebellum': tremorsWhenStandingCerebellum,
    'c1C5Myelopathy': tremorsWhenStandingC1C5Myelopathy,
    'c6T2Myelopathy': tremorsWhenStandingC6T2Myelopathy,
    't3L3Myelopathy': tremorsWhenStandingT3L3Myelopathy,
    'l4S3Myelopathy': tremorsWhenStandingL4S3Myelopathy,
    'motorUnit': tremorsWhenStandingMotorUnit,
    'neuromuscular': tremorsWhenStandingNeuromuscular,
    'systemicIllness': tremorsWhenStandingSystemicIllness,
    'intracranial': tremorsWhenStandingIntracranial,
    'nonSpecificPain': tremorsWhenStandingNonSpecificPain,
    'myopathy': tremorsWhenStandingMyopathy,
    'peripheralNeuropathy': tremorsWhenStandingPeripheralNeuropathy,
    'openEtiology': tremorsWhenStandingOpenEtiology,
    'cervicalPain': tremorsWhenStandingCervicalPain,
},
'paroxysmalEvent': {
    'forebrain': paroxysmalEventForebrain,
    'rightForebrain': paroxysmalEventRightForebrain,
    'leftForebrain': paroxysmalEventLeftForebrain,
    'intracranial': paroxysmalEventIntracranial,
    'openEtiology': paroxysmalEventOpenEtiology,
},
'myoclonusCervical': {
    'c1C5Myelopathy': myoclonusCervicalC1C5Myelopathy,
    'c6T2Myelopathy': myoclonusCervicalC6T2Myelopathy,
    'centralCordSyndrome': myoclonusCervicalCentralCordSyndrome,
    'systemicIllness': myoclonusCervicalSystemicIllness,
    'intracranial': myoclonusCervicalIntracranial,
    'nonSpecificPain': myoclonusCervicalNonSpecificPain,
    'openEtiology': myoclonusCervicalOpenEtiology,
    'cervicalPain': myoclonusCervicalCervicalPain,
},
'myoclonusConstant': {
    'intracranial': myoclonusConstantIntracranial,
    'openEtiology': myoclonusConstantOpenEtiology,
},
'myoclonusEpisodic': {
    'forebrain': myoclonusEpisodicForebrain,
    'rightForebrain': myoclonusEpisodicRightForebrain,
    'leftForebrain': myoclonusEpisodicLeftForebrain,
    'systemicIllness': myoclonusEpisodicSystemicIllness,
    'intracranial': myoclonusEpisodicIntracranial,
    'openEtiology': myoclonusEpisodicOpenEtiology,
},

  'myokymia': {
  'neuromuscular': myokymiaNeuromuscular,
  'systemicIllness': myokymiaSystemicIllness,
  'peripheralNeuropathy': myokymiaPeripheralNeuropathy,
  'openEtiology': myokymiaOpenEtiology,
  },
  'neuroMyotonia': {
      'neuromuscular': neuroMyotoniaNeuromuscular,
      'systemicIllness': neuroMyotoniaSystemicIllness,
      'peripheralNeuropathy': neuroMyotoniaPeripheralNeuropathy,
      'openEtiology': neuroMyotoniaOpenEtiology,
  },
  'narcolepsy': {
      'forebrain': narcolepsyForebrain,
      'rightForebrain': narcolepsyRightForebrain,
      'leftForebrain': narcolepsyLeftForebrain,
      'intracranial': narcolepsyIntracranial,
  },
  'headSwaying': {
      'vestibular': headSwayingVestibular,
  },
  'alert': {
      'normalExam': alertNormalExam,
      'forebrain': alertForebrain,
      'rightForebrain': alertRightForebrain,
      'leftForebrain': alertLeftForebrain,
      'brainstem': alertBrainstem,
      'systemicIllness': alertSystemicIllness,
      'intracranial': alertIntracranial,
  },
  'lethargic': {
      'forebrain': lethargicForebrain,
      'rightForebrain': lethargicRightForebrain,
      'leftForebrain': lethargicLeftForebrain,
      'brainstem': lethargicBrainstem,
      'vestibular': lethargicVestibular,
      'rightCentralVestibular': lethargicRightCentralVestibular,
      'leftCentralVestibular': lethargicLeftCentralVestibular,
      'rightCerebellumParadoxical': lethargicRightCerebellumParadoxical,
      'leftCerebellumParadoxical': lethargicLeftCerebellumParadoxical,
      'systemicIllness': lethargicSystemicIllness,
      'intracranial': lethargicIntracranial,
  },
  'obtunded': {
      'forebrain': obtundedForebrain,
      'rightForebrain': obtundedRightForebrain,
      'leftForebrain': obtundedLeftForebrain,
      'brainstem': obtundedBrainstem,
      'vestibular': obtundedVestibular,
      'rightCentralVestibular': obtundedRightCentralVestibular,
      'leftCentralVestibular': obtundedLeftCentralVestibular,
      'rightCerebellumParadoxical': obtundedRightCerebellumParadoxical,
      'leftCerebellumParadoxical': obtundedLeftCerebellumParadoxical,
      'systemicIllness': obtundedSystemicIllness,
      'intracranial': obtundedIntracranial,
  },
  'stuporous': {
      'brainstem': stuporousBrainstem,
      'rightCentralVestibular': stuporousRightCentralVestibular,
      'leftCentralVestibular': stuporousLeftCentralVestibular,
      'intracranial': stuporousIntracranial,
  },
  'comatose': {
      'brainstem': comatoseBrainstem,
      'intracranial': comatoseIntracranial,
  },
  'normalPosture': {
      'normalExam': normalPostureNormalExam,
      'vestibular': normalPostureVestibular,
      'rightPeripheralVestibular': normalPostureRightPeripheralVestibular,
      'rightCentralVestibular': normalPostureRightCentralVestibular,
      'leftPeripheralVestibular': normalPostureLeftPeripheralVestibular,
      'leftCentralVestibular': normalPostureLeftCentralVestibular,
      'rightCerebellumParadoxical': normalPostureRightCerebellumParadoxical,
      'leftCerebellumParadoxical': normalPostureLeftCerebellumParadoxical,
      'nerveRootSignature': normalPostureNerveRootSignature,
  },
  'headTiltRight': {
      'vestibular': headTiltRightVestibular,
      'rightPeripheralVestibular': headTiltRightRightPeripheralVestibular,
      'rightCentralVestibular': headTiltRightRightCentralVestibular,
      'leftPeripheralVestibular': headTiltRightLeftPeripheralVestibular,
      'leftCentralVestibular': headTiltRightLeftCentralVestibular,
      'cerebellum': headTiltRightCerebellum,
      'rightCerebellumParadoxical': headTiltRightRightCerebellumParadoxical,
      'leftCerebellumParadoxical': headTiltRightLeftCerebellumParadoxical,
      'intracranial': headTiltRightIntracranial,
  },
  'headTiltLeft': {
      'vestibular': headTiltLeftVestibular,
      'rightPeripheralVestibular': headTiltLeftRightPeripheralVestibular,
      'rightCentralVestibular': headTiltLeftRightCentralVestibular,
      'leftPeripheralVestibular': headTiltLeftLeftPeripheralVestibular,
      'leftCentralVestibular': headTiltLeftLeftCentralVestibular,
      'cerebellum': headTiltLeftCerebellum,
      'rightCerebellumParadoxical': headTiltLeftRightCerebellumParadoxical,
      'leftCerebellumParadoxical': headTiltLeftLeftCerebellumParadoxical,
      'intracranial': headTiltLeftIntracranial,
  },
  'headTurnRight': {
      'forebrain': headTurnRightForebrain,
      'rightForebrain': headTurnRightRightForebrain,
      'leftForebrain': headTurnRightLeftForebrain,
      'c1C5Myelopathy': headTurnRightC1C5Myelopathy,
      'c6T2Myelopathy': headTurnRightC6T2Myelopathy,
      'intracranial': headTurnRightIntracranial,
      'nonSpecificPain': headTurnRightNonSpecificPain,
      'cervicalPain': headTurnRightCervicalPain,
  },
  'headTurnLeft': {
      'forebrain': headTurnLeftForebrain,
      'rightForebrain': headTurnLeftRightForebrain,
      'leftForebrain': headTurnLeftLeftForebrain,
      'c1C5Myelopathy': headTurnLeftC1C5Myelopathy,
      'c6T2Myelopathy': headTurnLeftC6T2Myelopathy,
      'intracranial': headTurnLeftIntracranial,
      'nonSpecificPain': headTurnLeftNonSpecificPain,
      'cervicalPain': headTurnLeftCervicalPain,
  },
  'torticollis': {
      'c1C5Myelopathy': torticollisC1C5Myelopathy,
      'c6T2Myelopathy': torticollisC6T2Myelopathy,
      'cervicalPain': torticollisCervicalPain,
  },
  'neckGuarded': {
      'c1C5Myelopathy': neckGuardedC1C5Myelopathy,
      'c6T2Myelopathy': neckGuardedC6T2Myelopathy,
      'cervicalPain': neckGuardedCervicalPain,
  },
  'archerPosture': {
      'vestibular': archerPostureVestibular,
      'rightPeripheralVestibular': archerPostureRightPeripheralVestibular,
      'rightCentralVestibular': archerPostureRightCentralVestibular,
      'leftPeripheralVestibular': archerPostureLeftPeripheralVestibular,
      'leftCentralVestibular': archerPostureLeftCentralVestibular,
      'rightCerebellumParadoxical': archerPostureRightCerebellumParadoxical,
      'leftCerebellumParadoxical': archerPostureLeftCerebellumParadoxical,
      'intracranial': archerPostureIntracranial,
  },
  'holdingUpLimb': {
      'orthopedic': holdingUpLimbOrthopedic,
      'nerveRootSignature': holdingUpLimbNerveRootSignature,
  },
  'laterallyRecumbent': {
      'forebrain': laterallyRecumbentForebrain,
      'rightForebrain': laterallyRecumbentRightForebrain,
      'leftForebrain': laterallyRecumbentLeftForebrain,
      'brainstem': laterallyRecumbentBrainstem,
      'vestibular': laterallyRecumbentVestibular,
      'rightPeripheralVestibular': laterallyRecumbentRightPeripheralVestibular,
      'rightCentralVestibular': laterallyRecumbentRightCentralVestibular,
      'leftPeripheralVestibular': laterallyRecumbentLeftPeripheralVestibular,
      'leftCentralVestibular': laterallyRecumbentLeftCentralVestibular,
      'rightCerebellumParadoxical': laterallyRecumbentRightCerebellumParadoxical,
      'leftCerebellumParadoxical': laterallyRecumbentLeftCerebellumParadoxical,
      'c1C5Myelopathy': laterallyRecumbentC1C5Myelopathy,
      'c6T2Myelopathy': laterallyRecumbentC6T2Myelopathy,
      'motorUnit': laterallyRecumbentMotorUnit,
      'centralCordSyndrome': laterallyRecumbentCentralCordSyndrome,
      'intracranial': laterallyRecumbentIntracranial,
      'myopathy': laterallyRecumbentMyopathy,
  },
  'decerebrate': {
      'forebrain': decerebrateForebrain,
      'rightForebrain': decerebrateRightForebrain,
      'leftForebrain': decerebrateLeftForebrain,
      'brainstem': decerebrateBrainstem,
      'intracranial': decerebrateIntracranial,
  },
  'decerebellate': {
      'vestibular': decerebellateVestibular,
      'cerebellum': decerebellateCerebellum,
      'rightCerebellumParadoxical': decerebellateRightCerebellumParadoxical,
      'leftCerebellumParadoxical': decerebellateLeftCerebellumParadoxical,
  },

          'opisthotonus': {
      'forebrain': opisthotonusForebrain,
      'rightForebrain': opisthotonusRightForebrain,
      'leftForebrain': opisthotonusLeftForebrain,
      'brainstem': opisthotonusBrainstem,
      'vestibular': opisthotonusVestibular,
      'rightPeripheralVestibular': opisthotonusRightPeripheralVestibular,
      'rightCentralVestibular': opisthotonusRightCentralVestibular,
      'leftPeripheralVestibular': opisthotonusLeftPeripheralVestibular,
      'leftCentralVestibular': opisthotonusLeftCentralVestibular,
      'cerebellum': opisthotonusCerebellum,
      'rightCerebellumParadoxical': opisthotonusRightCerebellumParadoxical,
      'leftCerebellumParadoxical': opisthotonusLeftCerebellumParadoxical,
      'c1C5Myelopathy': opisthotonusC1C5Myelopathy,
      'c6T2Myelopathy': opisthotonusC6T2Myelopathy,
      't3L3Myelopathy': opisthotonusT3L3Myelopathy,
      'intracranial': opisthotonusIntracranial,
  },
  'schiffSherrington': {
      't3L3Myelopathy': schiffSherringtonT3L3Myelopathy,
      'l4S3Myelopathy': schiffSherringtonL4S3Myelopathy,
  },
  'kyphosis': {
      't3L3Myelopathy': kyphosisT3L3Myelopathy,
      'nonSpecificPain': kyphosisNonSpecificPain,
      'openEtiology': kyphosisOpenEtiology,
  },
  'scoliosis': {
      't3L3Myelopathy': scoliosisT3L3Myelopathy,
      'nonSpecificPain': scoliosisNonSpecificPain,
  },
  'diffuseRigidity': {
      'brainstem': diffuseRigidityBrainstem,
      'c1C5Myelopathy': diffuseRigidityC1C5Myelopathy,
      'motorUnit': diffuseRigidityMotorUnit,
      'peripheralNeuropathy': diffuseRigidityPeripheralNeuropathy,
  },
  'risusSardonicus': {
      'brainstem': risusSardonicusBrainstem,
  },
  'diffuseFlaccidity': {
      'motorUnit': diffuseFlaccidityMotorUnit,
      'neuromuscular': diffuseFlaccidityNeuromuscular,
      'peripheralNeuropathy': diffuseFlaccidityPeripheralNeuropathy,
  },
  'spasticThoracicLimbs': {
      'forebrain': spasticThoracicLimbsForebrain,
      'vestibular': spasticThoracicLimbsVestibular,
      'cerebellum': spasticThoracicLimbsCerebellum,
      'c1C5Myelopathy': spasticThoracicLimbsC1C5Myelopathy,
      't3L3Myelopathy': spasticThoracicLimbsT3L3Myelopathy,
  },
  'spasticPelvicLimbs': {
      'c6T2Myelopathy': spasticPelvicLimbsC6T2Myelopathy,
      't3L3Myelopathy': spasticPelvicLimbsT3L3Myelopathy,
  },
  'spasticAllLimbs': {
      'forebrain': spasticAllLimbsForebrain,
      'vestibular': spasticAllLimbsVestibular,
      'cerebellum': spasticAllLimbsCerebellum,
      'c1C5Myelopathy': spasticAllLimbsC1C5Myelopathy,
  },
  'crouchedPostureThoracicLimbs': {
      'c6T2Myelopathy': crouchedPostureThoracicLimbsC6T2Myelopathy,
      'centralCordSyndrome': crouchedPostureThoracicLimbsCentralCordSyndrome,
      'motorUnit': crouchedPostureThoracicLimbsMotorUnit,
      'neuromuscular': crouchedPostureThoracicLimbsNeuromuscular,
      'peripheralNeuropathy': crouchedPostureThoracicLimbsPeripheralNeuropathy,
      'myopathy': crouchedPostureThoracicLimbsMyopathy,
      'nonSpecificPain': crouchedPostureThoracicLimbsNonSpecificPain,
  },
  'crouchedPosturePelvicLimbs': {
      'l4S3Myelopathy': crouchedPosturePelvicLimbsL4S3Myelopathy,
      'motorUnit': crouchedPosturePelvicLimbsMotorUnit,
      'neuromuscular': crouchedPosturePelvicLimbsNeuromuscular,
      'peripheralNeuropathy': crouchedPosturePelvicLimbsPeripheralNeuropathy,
      'myopathy': crouchedPosturePelvicLimbsMyopathy,
      'caudaEquina': crouchedPosturePelvicLimbsCaudaEquina,
      'nonSpecificPain': crouchedPosturePelvicLimbsNonSpecificPain,
  },
  'crouchedPostureAllLimbs': {
      'motorUnit': crouchedPostureAllLimbsMotorUnit,
      'neuromuscular': crouchedPostureAllLimbsNeuromuscular,
      'peripheralNeuropathy': crouchedPostureAllLimbsPeripheralNeuropathy,
      'myopathy': crouchedPostureAllLimbsMyopathy,
      'nonSpecificPain': crouchedPostureAllLimbsNonSpecificPain,
  },
  'prayingPosture': {
      'nonSpecificPain': prayingPostureNonSpecificPain,
  },
  'ambulatoryNormal': {
      'normalExam': ambulatoryNormalNormalExam,
  },
  'ambulatoryLamenessThoracic': {
      'c1C5Myelopathy': ambulatoryLamenessThoracicC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryLamenessThoracicC6T2Myelopathy,
      'orthopedic': ambulatoryLamenessThoracicOrthopedic,
      'nerveRootSignature': ambulatoryLamenessThoracicNerveRootSignature,
      'nonSpecificPain': ambulatoryLamenessThoracicNonSpecificPain,
  },
  'ambulatoryLamenessPelvic': {
      'c1C5Myelopathy': ambulatoryLamenessPelvicC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryLamenessPelvicC6T2Myelopathy,
      'orthopedic': ambulatoryLamenessPelvicOrthopedic,
      'nerveRootSignature': ambulatoryLamenessPelvicNerveRootSignature,
      'nonSpecificPain': ambulatoryLamenessPelvicNonSpecificPain,
  },
  'ambulatoryMonoparesisThoracic': {
      'c6T2Myelopathy': ambulatoryMonoparesisThoracicC6T2Myelopathy,
      'orthopedic': ambulatoryMonoparesisThoracicOrthopedic,
      'nerveRootSignature': ambulatoryMonoparesisThoracicNerveRootSignature,
      'brachialPlexus': ambulatoryMonoparesisThoracicBrachialPlexus,
      'nonSpecificPain': ambulatoryMonoparesisThoracicNonSpecificPain,
  },
  'ambulatoryMonoparesisPelvic': {
      'l4S3Myelopathy': ambulatoryMonoparesisPelvicL4S3Myelopathy,
      'orthopedic': ambulatoryMonoparesisPelvicOrthopedic,
      'nerveRootSignature': ambulatoryMonoparesisPelvicNerveRootSignature,
      'caudaEquina': ambulatoryMonoparesisPelvicCaudaEquina,
      'aorticThromboembolism': ambulatoryMonoparesisPelvicAorticThromboembolism,
      'nonSpecificPain': ambulatoryMonoparesisPelvicNonSpecificPain,
  },
  'ambulatoryMonoplegiaThoracic': {
      'c6T2Myelopathy': ambulatoryMonoplegiaThoracicC6T2Myelopathy,
      'orthopedic': ambulatoryMonoplegiaThoracicOrthopedic,
      'nerveRootSignature': ambulatoryMonoplegiaThoracicNerveRootSignature,
      'brachialPlexus': ambulatoryMonoplegiaThoracicBrachialPlexus,
      'nonSpecificPain': ambulatoryMonoplegiaThoracicNonSpecificPain,
  },
  'ambulatoryMonoplegiaPelvic': {
      'l4S3Myelopathy': ambulatoryMonoplegiaPelvicL4S3Myelopathy,
      'orthopedic': ambulatoryMonoplegiaPelvicOrthopedic,
      'nerveRootSignature': ambulatoryMonoplegiaPelvicNerveRootSignature,
      'caudaEquina': ambulatoryMonoplegiaPelvicCaudaEquina,
      'aorticThromboembolism': ambulatoryMonoplegiaPelvicAorticThromboembolism,
      'nonSpecificPain': ambulatoryMonoplegiaPelvicNonSpecificPain,
  },
  'AmbulatoryParaparesisThoracic': {
      'c1C5Myelopathy': ambulatoryParaparesisThoracicC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryParaparesisThoracicC6T2Myelopathy,
      'orthopedic': ambulatoryParaparesisThoracicOrthopedic,
      'brachialPlexus': ambulatoryParaparesisThoracicBrachialPlexus,
      'motorUnit': ambulatoryParaparesisThoracicMotorUnit,
      'neuromuscular': ambulatoryParaparesisThoracicNeuromuscular,
      'centralCordSyndrome': ambulatoryParaparesisThoracicCentralCordSyndrome,
  },
  'AmbulatoryParaparesisPelvic': {
      't3L3Myelopathy': ambulatoryParaparesisPelvicT3L3Myelopathy,
      'l4S3Myelopathy': ambulatoryParaparesisPelvicL4S3Myelopathy,
      'caudaEquina': ambulatoryParaparesisPelvicCaudaEquina,
      'motorUnit': ambulatoryParaparesisPelvicMotorUnit,
      'neuromuscular': ambulatoryParaparesisPelvicNeuromuscular,
      'aorticThromboembolism': ambulatoryParaparesisPelvicAorticThromboembolism,
  },
  'AmbulatoryTetraparesis': {
      'forebrain': ambulatoryTetraparesisForebrain,
      'brainstem': ambulatoryTetraparesisBrainstem,
      'vestibular': ambulatoryTetraparesisVestibular,
      'rightCentralVestibular': ambulatoryTetraparesisRightCentralVestibular,
      'leftCentralVestibular': ambulatoryTetraparesisLeftCentralVestibular,
      'cerebellum': ambulatoryTetraparesisCerebellum,
      'c1C5Myelopathy': ambulatoryTetraparesisC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryTetraparesisC6T2Myelopathy,
      'motorUnit': ambulatoryTetraparesisMotorUnit,
      'neuromuscular': ambulatoryTetraparesisNeuromuscular,
      'intracranial': ambulatoryTetraparesisIntracranial,
  },

        'AmbulatoryShortStridedThoracic': {
      'c6T2Myelopathy': ambulatoryShortStridedThoracicC6T2Myelopathy,
      'orthopedic': ambulatoryShortStridedThoracicOrthopedic,
      'brachialPlexus': ambulatoryShortStridedThoracicBrachialPlexus,
      'motorUnit': ambulatoryShortStridedThoracicMotorUnit,
      'neuromuscular': ambulatoryShortStridedThoracicNeuromuscular,
      'centralCordSyndrome': ambulatoryShortStridedThoracicCentralCordSyndrome,
      'behavioral': ambulatoryShortStridedThoracicBehavioral,
      'myopathy': ambulatoryShortStridedThoracicMyopathy,
      'peripheralNeuropathy': ambulatoryShortStridedThoracicPeripheralNeuropathy,
  },
  'AmbulatoryShortStridedPelvic': {
      'l4S3Myelopathy': ambulatoryShortStridedPelvicL4S3Myelopathy,
      'caudaEquina': ambulatoryShortStridedPelvicCaudaEquina,
      'motorUnit': ambulatoryShortStridedPelvicMotorUnit,
      'neuromuscular': ambulatoryShortStridedPelvicNeuromuscular,
      'aorticThromboembolism': ambulatoryShortStridedPelvicAorticThromboembolism,
      'myopathy': ambulatoryShortStridedPelvicMyopathy,
      'peripheralNeuropathy': ambulatoryShortStridedPelvicPeripheralNeuropathy,
  },
  'AmbulatoryShortStridedAll': {
      'motorUnit': ambulatoryShortStridedAllMotorUnit,
      'neuromuscular': ambulatoryShortStridedAllNeuromuscular,
      'myopathy': ambulatoryShortStridedAllMyopathy,
  },
  'Ambulatory2EngineGait': {
      'c6T2Myelopathy': ambulatory2EngineGaitC6T2Myelopathy,
  },
  'AmbulatoryParaparesisPelvicProprioceptiveAtaxia': {
      't3L3Myelopathy': ambulatoryParaparesisPelvicProprioceptiveAtaxiaT3L3Myelopathy,
      'l4S3Myelopathy': ambulatoryParaparesisPelvicProprioceptiveAtaxiaL4S3Myelopathy,
      'caudaEquina': ambulatoryParaparesisPelvicProprioceptiveAtaxiaCaudaEquina,
  },
  'AmbulatoryTetraparesisProprioceptiveAtaxia': {
      'forebrain': ambulatoryTetraparesisProprioceptiveAtaxiaForebrain,
      'brainstem': ambulatoryTetraparesisProprioceptiveAtaxiaBrainstem,
      'vestibular': ambulatoryTetraparesisProprioceptiveAtaxiaVestibular,
      'rightCentralVestibular': ambulatoryTetraparesisProprioceptiveAtaxiaRightCentralVestibular,
      'leftCentralVestibular': ambulatoryTetraparesisProprioceptiveAtaxiaLeftCentralVestibular,
      'cerebellum': ambulatoryTetraparesisProprioceptiveAtaxiaCerebellum,
      'c1C5Myelopathy': ambulatoryTetraparesisProprioceptiveAtaxiaC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryTetraparesisProprioceptiveAtaxiaC6T2Myelopathy,
      'intracranial': ambulatoryTetraparesisProprioceptiveAtaxiaIntracranial,
  },
  'AmbulatoryProprioceptiveAtaxiaPelvic': {
      't3L3Myelopathy': ambulatoryProprioceptiveAtaxiaPelvicT3L3Myelopathy,
  },
  'AmbulatoryProprioceptiveAtaxiaAll': {
      'forebrain': ambulatoryProprioceptiveAtaxiaAllForebrain,
      'c1C5Myelopathy': ambulatoryProprioceptiveAtaxiaAllC1C5Myelopathy,
      'brainstem': ambulatoryProprioceptiveAtaxiaAllBrainstem,
  },
  'AmbulatoryFatiguable': {
      'neuromuscular': ambulatoryFatiguableNeuromuscular,
      'motorUnit': ambulatoryFatiguableMotorUnit,
      'myopathy': ambulatoryFatiguableMyopathy,
  },
  'AmbulatoryTetraparesisVestibularAtaxia': {
      'brainstem': ambulatoryTetraparesisVestibularAtaxiaBrainstem,
      'vestibular': ambulatoryTetraparesisVestibularAtaxiaVestibular,
      'rightPeripheralVestibular': ambulatoryTetraparesisVestibularAtaxiaRightPeripheralVestibular,
      'rightCentralVestibular': ambulatoryTetraparesisVestibularAtaxiaRightCentralVestibular,
      'leftPeripheralVestibular': ambulatoryTetraparesisVestibularAtaxiaLeftPeripheralVestibular,
      'leftCentralVestibular': ambulatoryTetraparesisVestibularAtaxiaLeftCentralVestibular,
      'rightCerebellumParadoxical': ambulatoryTetraparesisVestibularAtaxiaRightCerebellumParadoxical,
      'leftCerebellumParadoxical': ambulatoryTetraparesisVestibularAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryTetraparesisCerebellarAtaxia': {
      'cerebellum': ambulatoryTetraparesisCerebellarAtaxiaCerebellum,
      'rightCerebellumParadoxical': ambulatoryTetraparesisCerebellarAtaxiaRightCerebellumParadoxical,
      'leftCerebellumParadoxical': ambulatoryTetraparesisCerebellarAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryVestibularAtaxia': {
      'brainstem': ambulatoryVestibularAtaxiaBrainstem,
      'vestibular': ambulatoryVestibularAtaxiaVestibular,
      'rightPeripheralVestibular': ambulatoryVestibularAtaxiaRightPeripheralVestibular,
      'rightCentralVestibular': ambulatoryVestibularAtaxiaRightCentralVestibular,
      'leftPeripheralVestibular': ambulatoryVestibularAtaxiaLeftPeripheralVestibular,
      'leftCentralVestibular': ambulatoryVestibularAtaxiaLeftCentralVestibular,
      'cerebellum': ambulatoryVestibularAtaxiaCerebellum,
  },
  'AmbulatoryCerebellarAtaxia': {
      'cerebellum': ambulatoryCerebellarAtaxiaCerebellum,
      'rightCerebellumParadoxical': ambulatoryCerebellarAtaxiaRightCerebellumParadoxical,
      'leftCerebellumParadoxical': ambulatoryCerebellarAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryMixedAtaxia': {
      'brainstem': ambulatoryMixedAtaxiaBrainstem,
      'rightCentralVestibular': ambulatoryMixedAtaxiaRightCentralVestibular,
  },
  'AmbulatoryMixedAtaxiaTetraparesis': {
      'leftCentralVestibular': ambulatoryMixedAtaxiaTetraparesisLeftCentralVestibular,
      'cerebellum': ambulatoryMixedAtaxiaTetraparesisCerebellum,
      'rightCerebellumParadoxical': ambulatoryMixedAtaxiaTetraparesisRightCerebellumParadoxical,
      'leftCerebellumParadoxical': ambulatoryMixedAtaxiaTetraparesisLeftCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisLeft': {
      'rightForebrain': ambulatoryHemiparesisLeftRightForebrain,
      'leftForebrain': ambulatoryHemiparesisLeftLeftForebrain,
      'brainstem': ambulatoryHemiparesisLeftBrainstem,
      'leftCentralVestibular': ambulatoryHemiparesisLeftLeftCentralVestibular,
      'leftCerebellumParadoxical': ambulatoryHemiparesisLeftLeftCerebellumParadoxical,
      'c1C5Myelopathy': ambulatoryHemiparesisLeftC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryHemiparesisLeftC6T2Myelopathy,
  },
  'AmbulatoryHemiparesisLeftProprioceptiveAtaxia': {
      'rightForebrain': ambulatoryHemiparesisLeftProprioceptiveAtaxiaRightForebrain,
      'leftForebrain': ambulatoryHemiparesisLeftProprioceptiveAtaxiaLeftForebrain,
      'brainstem': ambulatoryHemiparesisLeftProprioceptiveAtaxiaBrainstem,
      'c1C5Myelopathy': ambulatoryHemiparesisLeftProprioceptiveAtaxiaC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryHemiparesisLeftProprioceptiveAtaxiaC6T2Myelopathy,
  },
  'AmbulatoryHemiparesisLeftCerebellarAtaxia': {
      'leftCerebellumParadoxical': ambulatoryHemiparesisLeftCerebellarAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisLeftMixedAtaxia': {
      'brainstem': ambulatoryHemiparesisLeftMixedAtaxiaBrainstem,
      'leftCentralVestibular': ambulatoryHemiparesisLeftMixedAtaxiaLeftCentralVestibular,
      'leftCerebellumParadoxical': ambulatoryHemiparesisLeftMixedAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisLeftVestibularAtaxia': {
      'brainstem': ambulatoryHemiparesisLeftVestibularAtaxiaBrainstem,
      'leftCentralVestibular': ambulatoryHemiparesisLeftVestibularAtaxiaLeftCentralVestibular,
      'leftCerebellumParadoxical': ambulatoryHemiparesisLeftVestibularAtaxiaLeftCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisRight': {
      'leftForebrain': ambulatoryHemiparesisRightLeftForebrain,
      'rightForebrain': ambulatoryHemiparesisRightRightForebrain,
      'brainstem': ambulatoryHemiparesisRightBrainstem,
      'rightCentralVestibular': ambulatoryHemiparesisRightRightCentralVestibular,
      'rightCerebellumParadoxical': ambulatoryHemiparesisRightRightCerebellumParadoxical,
      'c1C5Myelopathy': ambulatoryHemiparesisRightC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryHemiparesisRightC6T2Myelopathy,
  },
  'AmbulatoryHemiparesisRightProprioceptiveAtaxia': {
      'leftForebrain': ambulatoryHemiparesisRightProprioceptiveAtaxiaLeftForebrain,
      'rightForebrain': ambulatoryHemiparesisRightProprioceptiveAtaxiaRightForebrain,
      'brainstem': ambulatoryHemiparesisRightProprioceptiveAtaxiaBrainstem,
      'c1C5Myelopathy': ambulatoryHemiparesisRightProprioceptiveAtaxiaC1C5Myelopathy,
      'c6T2Myelopathy': ambulatoryHemiparesisRightProprioceptiveAtaxiaC6T2Myelopathy,
  },
  'AmbulatoryHemiparesisRightCerebellarAtaxia': {
      'rightCerebellumParadoxical': ambulatoryHemiparesisRightCerebellarAtaxiaRightCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisRightMixedAtaxia': {
      'brainstem': ambulatoryHemiparesisRightMixedAtaxiaBrainstem,
      'rightCentralVestibular': ambulatoryHemiparesisRightMixedAtaxiaRightCentralVestibular,
      'rightCerebellumParadoxical': ambulatoryHemiparesisRightMixedAtaxiaRightCerebellumParadoxical,
  },
  'AmbulatoryHemiparesisRightVestibularAtaxia': {
      'brainstem': ambulatoryHemiparesisRightVestibularAtaxiaBrainstem,
      'rightCentralVestibular': ambulatoryHemiparesisRightVestibularAtaxiaRightCentralVestibular,
      'rightCerebellumParadoxical': ambulatoryHemiparesisRightVestibularAtaxiaRightCerebellumParadoxical,
  },
  };
    
}
